FORMAT: 1A
HOST: https://localhost:8080

# AgendaService

AgendaService is a simple API allowing users to manage their schedules online.

# Group User

A User object has the following attributes:

+ username (string)
+ password (string)
+ email (string)

  
# Group Access Authorization and Control

Access and Control of Authorization.

## Authentication [/v1/auth{?username,password,token}]

Authorization Resource represents an authorization granted to the user. You can **only** access your own authorization.

The Authorization Resource has the following attribute:

+ token


### Retrieve Authorization [GET]

Get an Authentication token for operations later. It takes a JSON object containing a username and a password of as parament. If fails, the token should be empty.

+ Parameters
    - username : `VinaLx` (string, required) - User Name
    - password : `vpass` (string, required) - User Password


+ Response 200 (application/json)

        {
            "token":"1a2b3c"
        }


### Remove an Authorization [DELETE]

Remove an Authorization token from database.

+ Parameters
    - token : `1a2b3c` (string, required) - Auth Token

+ Response 204


# Group Users

Resources related to a users collection in the API.

## Users Collection [/v1/users{?token}]
  
It contains the operations of users collection.


### Create A User [POST]

To create a new account. It takes a JSON object containing a username, a password and a email address as its parament. The username should be unique.

+ username (string) - User's name
+ password (string) - User's password
+ email (string) - User's email address

+ Request (application/json)

        {
            "username":"VinaLx"
            "password":"vpass"
            "email":"VinaLx@mail2.sysu.edu.cn"
        }

+ Response 201 (application/json)

        {
            "username":"VinaLx"
            "password":"vpass"
            "email":"VinaLx@mail2.sysu.edu.cn"
        }

### List all Users [GET]

To view all the users.

+ Parameters
    - token : `1a2b3c` (string, required) - Auth Token

+ Response 200 (application/json)

        [
            {
                "username":"VinaLx"
                "password":"vpass"
                "email":"VinaLx@mail2.sysu.edu.cn"
            }, {
                "username":"ZexinYan"
                "password":"zpass"
                "email":"ZexinYan@mail2.sysu.edu.cn"
            }, {
                "username":"Jarvis"
                "password":"jpass"
                "email":"Jarvis@mail2.sysu.edu.cn"
            }
        ]
   
### Delete a User [DELETE /v1/users/{username}]

To delete the user account with username from database.

+ Response 204