FORMAT: 1A
HOST: http://agendaservice12.apiblueprint.org/

# AgendaService

AgendaService is a simple API allowing users to manage their schedules online.

# Group User

Resource operations related to a user in the API.

A User object has the following attributes:

+ username (string)
+ password (string)
+ email (string)


## AgendaService API Root [/]

### User Log In [POST /login]

To log in. It takes a JSON object containing the username and the  password of a user as parament.

+ username (string) - User's name
+ password (string) - User's password

+ Request (application/json)

        {
            "username":"VinaLx"
            "password":"vpass"
        }

+ Response 201 (application/json)

    + Headers

            Location: /welcome

    + Body

            {
                "token":"1a2b3c"
            }

### User Register [POST /register]

To register a new account. It takes a JSON object containing a username, a password and a email address as its parament. The username should be unique.

+ username (string) - User's name
+ password (string) - User's password
+ email (string) - User's email address

+ Request (application/json)

        {
            "username":"VinaLx"
            "password":"vpass"
            "email":"VinaLx@mail2.sysu.edu.cn"
        }

+ Response 201 (application/json)

    + Headers

            Location: /welcome

    + Body

            {
                "username":"VinaLx"
                "password":"vpass"
                "email":"VinaLx@mail2.sysu.edu.cn"
            }


## User Operations [/welcome{?token}]

It contains the operations of a user when logged in. The token was generated after logged in.

+ Parameters
    - token : `1a2b3c` (string, required) - Auth Token

### List all Users [GET]

To view all the users.

+ Response 200 (application/json)

        [
            {
                "username":"VinaLx"
                "password":"vpass"
                "email":"VinaLx@mail2.sysu.edu.cn"
            }, {
                "username":"ZexinYan"
                "password":"zpass"
                "email":"ZexinYan@mail2.sysu.edu.cn"
            }, {
                "username":"Jarvis"
                "password":"jpass"
                "email":"Jarvis@mail2.sysu.edu.cn"
            }
        ]

### User Log Out [POST]

To log out and the token will be removed.

+ Response 204

### Delete a User [DELETE]

To delete the user account from database.

+ Response 204
